frontendlb:
  ports:
  - 80:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - frontend:frontend
  stdin_open: true
frontend:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: node
  links:
  - database:database
  stdin_open: true
database:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mongo
  stdin_open: true
